# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import movies_pb2 as movies__pb2


class MovieServiceStub(object):
    """Represents movie service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.recommendMovie = channel.unary_unary(
                '/MovieService/recommendMovie',
                request_serializer=movies__pb2.MovieRecommendationRequest.SerializeToString,
                response_deserializer=movies__pb2.MovieRecommendationResponse.FromString,
                )


class MovieServiceServicer(object):
    """Represents movie service
    """

    def recommendMovie(self, request, context):
        """Reponsible for recommending movies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'recommendMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.recommendMovie,
                    request_deserializer=movies__pb2.MovieRecommendationRequest.FromString,
                    response_serializer=movies__pb2.MovieRecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MovieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MovieService(object):
    """Represents movie service
    """

    @staticmethod
    def recommendMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MovieService/recommendMovie',
            movies__pb2.MovieRecommendationRequest.SerializeToString,
            movies__pb2.MovieRecommendationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
