# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmovies.proto\"=\n\x1aMovieRecommendationRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"4\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\"5\n\x1bMovieRecommendationResponse\x12\x16\n\x06movies\x18\x01 \x03(\x0b\x32\x06.Movie2[\n\x0cMovieService\x12K\n\x0erecommendMovie\x12\x1b.MovieRecommendationRequest\x1a\x1c.MovieRecommendationResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIERECOMMENDATIONREQUEST._serialized_start=16
  _MOVIERECOMMENDATIONREQUEST._serialized_end=77
  _MOVIE._serialized_start=79
  _MOVIE._serialized_end=131
  _MOVIERECOMMENDATIONRESPONSE._serialized_start=133
  _MOVIERECOMMENDATIONRESPONSE._serialized_end=186
  _MOVIESERVICE._serialized_start=188
  _MOVIESERVICE._serialized_end=279
# @@protoc_insertion_point(module_scope)
